# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'image.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from gettext import gettext
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QApplication, QWidget, QPushButton, QAction, QLineEdit, QMessageBox
from PyQt5.QtGui import QIcon
from PyQt5.QtCore import pyqtSlot



import cv2
import os
flag=0
name="name"
img_name="d"


class Ui_MainWindow(object):
    
    
    def capture(self):
            print("clicked")
            cam=cv2.VideoCapture(0)
            cv2.namedWindow("Python Webcam")
            img_counter=0
            flag=0
            while flag==0:
                ret,frame=cam.read()

                if not ret:
                  print("Failed")
                  break

                cv2.imshow("test",frame)
                k=cv2.waitKey(1) 
                #if k%256 == 27: 
                 # print("Escape Hit!!Closing")
                  #break

                if k%256 == 32:
                  img_name = "opencv_frame_{}.png".format(img_counter)
                  cv2.imwrite(img_name,frame)
                  print("Picture taken")
                  cv2.imshow(img_name,frame)
                  #self.retake()
                  #break
                  #img_counter+=1
                  flag=flag+1

            cam.release()

            cv2.destroyWindow("test")

    def retake(self):
            self.capture()
    def save(self):
        cv2.destroyWindow("opencv_frame_0.png")
        print("Saved")
        cv2.destroyAllWindows()
        quit()
    #    name=self.namefield.text()
     #   name2=".png"
      #  name3= " ".join([name,name2])
        #cv2.imwrite(name3,name3)
       # os. rename(img_name,name3) 
    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(676, 495)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.capturebutton = QtWidgets.QPushButton(self.centralwidget)
        self.capturebutton.setGeometry(QtCore.QRect(240, 170, 221, 41))
        self.capturebutton.setObjectName("capturebutton")
        self.capturebutton.clicked.connect(self.capture)

        self.retakebutton = QtWidgets.QPushButton(self.centralwidget)
        self.retakebutton.setGeometry(QtCore.QRect(240, 220, 131, 41))
        self.retakebutton.setObjectName("retakebutton")
        self.retakebutton.clicked.connect(self.retake)
        
        self.savebutton = QtWidgets.QPushButton(self.centralwidget)
        self.savebutton.setGeometry(QtCore.QRect(240, 270, 131, 41))
        self.savebutton.setObjectName("savebutton")
        self.savebutton.clicked.connect(self.save)
        
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 50, 141, 61))
        self.label.setObjectName("label")
        self.enternamelabel = QtWidgets.QLabel(self.centralwidget)
        self.enternamelabel.setGeometry(QtCore.QRect(240, 120, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.enternamelabel.setFont(font)
        self.enternamelabel.setObjectName("enternamelabel")

        self.namefield = QtWidgets.QLineEdit(self.centralwidget)
        self.namefield.setGeometry(QtCore.QRect(380, 120, 161, 41))
        self.namefield.setObjectName("namefield")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 676, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.capturebutton.setText(_translate("MainWindow", "Capturte Image"))
        self.retakebutton.setText(_translate("MainWindow", "Retake"))
        self.savebutton.setText(_translate("MainWindow", "Save"))
        self.label.setText(_translate("MainWindow", "Add New Member!"))
        self.enternamelabel.setText(_translate("MainWindow", "Enter name:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
